services:
  clientservice:
    build:
      context: . # Build context is the root of your microbank project
      dockerfile: ./services/clientservice/Dockerfile # Explicitly point to the Dockerfile
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET=your-secret-from-bezkoder-app-properties
    networks:
      - microbank
    depends_on:
      db:
        condition: service_healthy # Ensure DB is ready before clientservice starts

  bankingservice:
    build:
      context: . # Build context is the root of your microbank project
      dockerfile: ./services/bankingservice/Dockerfile # Explicitly point to the Dockerfile
    ports:
      - "8082:8082"
    environment:
      - CLIENT_SERVICE_URL=http://clientservice:8081
    depends_on:
      clientservice: # bankingservice needs clientservice to be up for inter-service communication
        condition: service_started
      db:
        condition: service_healthy # bankingservice also needs DB to be ready
    networks:
      - microbank

  db:
  image: postgres:15
  container_name: postgres_db
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: banking_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: your_password_here
  volumes:
    - db_data:/var/lib/postgresql/data
  networks:
    - microbank
  healthcheck:
    test: ["CMD", "pg_isready", "-U", "postgres"]
    interval: 5s
    timeout: 20s
    retries: 10
    start_period: 30s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_web
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ""
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microbank

networks:
  microbank:
    driver: bridge

volumes:
  db_data: